working_directory = "/Users/nodo"

# Download catppuccin-mocha using:
# curl -LO --output-dir ~/.config/alacritty https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[bell]
duration = 0

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Comma"
mods = "Command"

[scrolling]
history = 10000

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
startup_mode = "SimpleFullscreen"

[window.padding]
x = 10
y = 10
